# General
max_turtles: 8

# ROS topic queue size
queue_size: 100

# Collision parameters
turtle_radius: 1.0 # [units]
collision_range: 2.0 # [units]
obstacle_field_range: 6.0 # [units]
goal_tolerance: 0.5 # [units]
goal_timeout: 5 # [s]

# Simulation
sim: true
time_step: 0.1 # [s]

# Boundary
boundary:
  x_min: -10 # [units]
  x_max:  10 # [units]
  y_min: -10 # [units]
  y_max:  10 # [units]
